# Generated by Django 3.2.5 on 2022-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangouploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='image',
            field=models.ImageField(upload_to='djangouploads/files/covers/'),
        ),
    ]
