# Generated by Django 3.2.5 on 2022-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangouploads', '0003_auto_20220815_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
