# Generated by Django 3.2.15 on 2022-08-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangouploads', '0004_drink_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='name',
            new_name='doc_name',
        ),
    ]
