# Generated by Django 3.2.15 on 2022-08-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangouploads', '0005_rename_name_drink_doc_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='doc_name',
            new_name='name',
        ),
    ]
